language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: VUBntdV0OHGG1Yr6A0UR0YoFGiPyY3S/PZKguNhgNobiOPcg/V3HVNUhymJJvhRsrz5GLPoAYayfXra4at06e99voKfFc5QpZI3nA2Nja8dB4h+4Y2BLXw71UpXULU8fi3wdd2g4SNXz+UTpRYbqlEf64Sdm+7EsgLdiCNpdpk8=
